### ISSUE TITLE
Update php packages with --with-dependencies

### ISSUE THREAD

**Issue by floretan** [dependabot/feedback#26]
We had an issue where a PR created by dependabot updated one of the packages, but didn't update the dependent package which caused an error. In this specific case there were some issues with a missing stability requirement in the package's composer.json, but in general it would be nice to run composer updates with the `--with-dependencies` parameter, or at least to make that an option.

**Comment by greysteil** [comment]
Done in https://github.com/dependabot/dependabot-core/commit/7f1097a5bc2be85cd79d036a7454a4dd8f5be1a8, which is now live. I'm relatively confident this is an option that everyone will want enabled, but will revisit making it configurable if it causes any trouble.

Thanks for the feedback!

**Comment by chekalskiy** [comment]
@greysteil Please take a look — we have same issue and it still persists. I've just run `composer update` in our master branch and it shows a lot of outdated dependencies. Thanks

**Comment by greysteil** [comment]
@chekalskiy that option is still enabled, and should be working, but if there are sub-dependencies that have received an update when their top-level dependency hasn't then Dependabot won't yet have updated them for you.

Can you confirm that none of the outdated dependencies are top-level? (i.e., that they don't appear in your `composer.json`)? Happy to take a look at the repo myself if that's easier and you ping me the details (support@dependabot.com).
