### ISSUE TITLE
How to access error logs

### ISSUE THREAD

**Issue by johannessteu** [dependabot/feedback#450]
I keep getting an error on a php project with composer. Is there any way to see logs why it failed? I'm not sure if the bot can handle a configuration like this with local paths:

```
{
  "name": "some/name",
  "description": "some description",
  "config": {
    "vendor-dir": "Packages/Libraries",
    "bin-dir": "bin"
  },
  "require": {
    "php" : "~7.2.0",
    "neos/flow": "~5.2.3",
    "t3n/graphql": "~1.0.1",
    // [...] some more deps

    "t3n/package-name": "@dev"
  },
  "repositories": {
    "distributionPackages": {
      "type": "path",
      "url": "./t3nPackages/*"
    }
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "scripts": {
    "post-update-cmd": "Neos\\Flow\\Composer\\InstallerScripts::postUpdateAndInstall",
    "post-install-cmd": "Neos\\Flow\\Composer\\InstallerScripts::postUpdateAndInstall",
    "post-package-update": "Neos\\Flow\\Composer\\InstallerScripts::postPackageUpdateAndInstall",
    "post-package-install": "Neos\\Flow\\Composer\\InstallerScripts::postPackageUpdateAndInstall"
  }
}
```

**Comment by johannessteu** [comment]
I was able to test my setup with the `dependabot-script`. Looks like we missed some access tokens. Closing for now, but some kind of error logs would still be nice!

**Comment by greysteil** [comment]
Good to hear!

**Comment by johannessteu** [comment]
Hmm, at another project with a composer setup like in the initial description i get this error when running `dependabot-script`:

```
/Users/hannes/.rvm/gems/ruby-2.6.2/gems/dependabot-common-0.106.20/lib/dependabot/shared_helpers.rb:112:in `run_helper_subprocess': Source path "./t3nPackages/ContentApi.Elastic" is not found for package t3n/contentapi-elastic (Dependabot::SharedHelpers::HelperSubprocessFailed)
```

There might be a problem with composer path type @greysteil ?!

**Comment by johannessteu** [comment]
Also, is it possible to fetch repos from a prvate gitlab instance as well as private github repos? I configured both access tokens in dependabot dashboard, but looks like the job times out. The dependabot-script also looks like there is only on set of credentials configured?

**Comment by greysteil** [comment]
@johannessteu how are you running this? It's hard for me to debug script issues since I can't replicate them, but in general I'd recommend ruby a ruby console and stepping through each command in the script to isolate where the error is occurring.

**Comment by johannessteu** [comment]
I'll try to setup a example repo! Unfortunately i'm not that deep into ruby but i'll ty to dig deeper

**Comment by johannessteu** [comment]
@greysteil  here we go:

https://github.com/johannessteu/dependabot-composer-demo/

This is a public repo using composers [`path`](https://getcomposer.org/doc/05-repositories.md#path) option wich symlinks local folders to your app

I'm running the `generic-update-script.rb` script and configured a github access token etc.

```
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.3-compliant syntax, but you are running 2.6.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
[{"type"=>"git_source", "host"=>"github.com", "username"=>"x-access-token", "password"=>"some-token"}]Fetching composer dependency files for johannessteu/dependabot-composer-demo
Parsing dependencies information
  - Updating neos/flow (from 5.2.4)…Traceback (most recent call last):
	15: from generic-update-script.rb:118:in `<main>'
	14: from generic-update-script.rb:118:in `each'
	13: from generic-update-script.rb:156:in `block in <main>'
	12: from /Users/hannes/.rvm/gems/ruby-2.6.2/gems/dependabot-composer-0.106.20/lib/dependabot/composer/file_updater.rb:34:in `updated_dependency_files'
	11: from /Users/hannes/.rvm/gems/ruby-2.6.2/gems/dependabot-composer-0.106.20/lib/dependabot/composer/file_updater.rb:64:in `updated_lockfile_content'
	10: from /Users/hannes/.rvm/gems/ruby-2.6.2/gems/dependabot-composer-0.106.20/lib/dependabot/composer/file_updater/lockfile_updater.rb:24:in `updated_lockfile_content'
	 9: from /Users/hannes/.rvm/gems/ruby-2.6.2/gems/dependabot-common-0.106.20/lib/dependabot/shared_helpers.rb:34:in `in_a_temporary_directory'
	 8: from /Users/hannes/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	 7: from /Users/hannes/.rvm/gems/ruby-2.6.2/gems/dependabot-common-0.106.20/lib/dependabot/shared_helpers.rb:37:in `block in in_a_temporary_directory'
	 6: from /Users/hannes/.rvm/gems/ruby-2.6.2/gems/dependabot-common-0.106.20/lib/dependabot/shared_helpers.rb:37:in `chdir'
	 5: from /Users/hannes/.rvm/gems/ruby-2.6.2/gems/dependabot-common-0.106.20/lib/dependabot/shared_helpers.rb:37:in `block (2 levels) in in_a_temporary_directory'
	 4: from /Users/hannes/.rvm/gems/ruby-2.6.2/gems/dependabot-composer-0.106.20/lib/dependabot/composer/file_updater/lockfile_updater.rb:27:in `block in updated_lockfile_content'
	 3: from /Users/hannes/.rvm/gems/ruby-2.6.2/gems/dependabot-composer-0.106.20/lib/dependabot/composer/file_updater/lockfile_updater.rb:53:in `run_update_helper'
	 2: from /Users/hannes/.rvm/gems/ruby-2.6.2/gems/dependabot-common-0.106.20/lib/dependabot/shared_helpers.rb:141:in `with_git_configured'
	 1: from /Users/hannes/.rvm/gems/ruby-2.6.2/gems/dependabot-composer-0.106.20/lib/dependabot/composer/file_updater/lockfile_updater.rb:54:in `block in run_update_helper'
/Users/hannes/.rvm/gems/ruby-2.6.2/gems/dependabot-common-0.106.20/lib/dependabot/shared_helpers.rb:112:in `run_helper_subprocess': Source path "./myPackages/Demo.Package" is not found for package johannessteu/demo-package (Dependabot::SharedHelpers::HelperSubprocessFailed)
```

Looks like there is an issue when resolving the local path? 
If i run a manual composer update within the `/app` folder composer does not complain at all:
```
11:08:47  ➜  app git:(master) ✗ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
PHP CodeSniffer Config installed_paths set to ../../t3n/coding-standard/src,../../slevomat/coding-standard
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> Neos\Flow\Composer\InstallerScripts::postUpdateAndInstall
```

**Comment by greysteil** [comment]
Oh, interesting, I've only ever seen Composer path dependencies specified [this way](https://getcomposer.org/doc/05-repositories.md#path).

Are there docs for using the `distributionPackages` setup? What's the difference?

**Comment by johannessteu** [comment]
@greysteil the `distributionPackages` itself is just a custom key, could be anything. But you can configure a source folder where composer searches for packages. So you can put like 10 packages in that folder and composer will find all those packages with a single configuration. Compared to the way you linked you would have to configure each package.

**Comment by greysteil** [comment]
Cool - working on a fix now.

**Comment by johannessteu** [comment]
It's actually the same thing you linked but with glob syntax (check the last note box)

**Comment by greysteil** [comment]
You can use glob syntax when specifying the repos as an array, too. I *think* it's just an old syntax, but if Composer supports it then Dependabot should too.

**Comment by greysteil** [comment]
Fixed in [this commit](https://github.com/dependabot/dependabot-core/commit/d411cd2dd0b2f49d36953069d762826bd665b447). Being released as `v0.106.22` now - I'll update the script to pull that in as soon as it's out.

**Comment by johannessteu** [comment]
A local `bundle update` and running the update script seems to work! PR's are already created :)
https://github.com/johannessteu/dependabot-composer-demo/pulls !

Awesome - Thanks a lot!

**Comment by johannessteu** [comment]
Is it already deployed to https://app.dependabot.com ? I still get an error on that repo

**Comment by greysteil** [comment]
It's deploying now - should be out in the next 5 mins.
