### ISSUE TITLE
Pre-release versions of NuGet packages not updated

### ISSUE THREAD

**Issue by JustArchi** [dependabot/feedback#451]
Hello.

Please refer to my `csproj` and the project **[here](https://github.com/JustArchiNET/ArchiSteamFarm/blob/9b9f45f26a1748fb21cb15ab14ef45f60f84dfd0/ArchiSteamFarm/ArchiSteamFarm.csproj)**.

I'm using several pre-release versions of NuGet packages, and to the best of my knowledge, dependabot is configured to automatically bump stable versions to newer stable releases, and pre-release versions to anything that is currently available.

I have at least 5 packages that are not being updated correctly, but to name one, **[Microsoft.Extensions.Logging.Configuration](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Configuration)**.

From my `csproj`:

```csproj
<PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="3.0.0-preview.19074.2" />
```

As we can see on the **[NuGet](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Configuration)**, the version that I'm using is a pre-release that is more than 3 months old, so there is no way of just a brief networking issue or anything, but wrong logic applied. The latest version (also pre-release) is `3.0.0-preview4.19216.2` as of today.

Could you please take a look what is wrong and why dependabot doesn't update this package? It's not the only one that suffers from that, but I believe that solving this one will also solve all other ones. You have my project that you can fork and make tests on if you'd like to.

I don't have anything special in the dependabot config:

![image](https://user-images.githubusercontent.com/1069029/56813896-3f410e80-683e-11e9-9db1-020e55747016.png)

Thank you in advance for looking into this issue.

**Comment by JustArchi** [comment]
This issue is more than 3 months old by now and I still consider this core functionality for C# projects, I hope you can get down to this soon guys.

**Comment by greysteil** [comment]
Looks like this is about fetching the `NuGet.config` file from nested directories, not pre-releases. Should be fixed by https://github.com/dependabot/dependabot-core/commit/1fb07ffb634a9d78e6f214bc3295b542882dccee, which I've just deployed.

**Comment by JustArchi** [comment]
Thank you a lot @greysteil! ❤️

**Comment by JustArchi** [comment]
@greysteil the bug is still here, I'm currently on `3.0.0-preview7.19362.4`, there is `3.0.0-preview8.19405.4` released 16 days ago and dependabot didn't offer update to it, both packages are pre-releases and both are from official nuget - **[link](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Json/3.0.0-preview8.19405.4)**.

**Comment by JustArchi** [comment]
In fact it didn't even update NLog 4.6.7 released 4 days ago, which is a stable release - **[link](https://www.nuget.org/packages/NLog/4.6.7)**.

Not sure what happened but it seems that no nuget packages are being updated at all right now.

**Comment by greysteil** [comment]
Should be fixed by https://github.com/dependabot/dependabot-core/commit/dfff22397eaf52ad08afa90270de3bacaeb711ef, which I'll get deployed today.

**Comment by JustArchi** [comment]
Thanks again ❤️

**Comment by mynkow** [comment]
I can say this is not fixed as of today.
