### ISSUE TITLE
Config file is not used if it was added after adding project

### ISSUE THREAD

**Issue by kolen** [dependabot/feedback#637]
We have projects which have `.dependabot/config.yml` file in repository, but Dependabot does not use it.

One of projects has this file and it's used by the system, as seen in this screenshot, but not others:

![image](https://user-images.githubusercontent.com/24191/63352874-8b263f00-c36a-11e9-9ca6-9cac99d818a3.png)

These projects, where it's unused, were added to dependabot earlier and `.dependabot/config.yml` was added after adding project. So, maybe, configs are not recognized if added later?

[Validator](https://dependabot.com/docs/config-file/validator/) shows "looks good" for these configs.

**Comment by greysteil** [comment]
Hard to debug this without the repo name - can you email the full name to support@dependabot.com?

**Comment by kolen** [comment]
@greysteil I sent email with repository names.

**Comment by kolen** [comment]
Similar issue: #634, but other way round: first config was added to repository, then project was added to Dependabot.

**Comment by rebelagentm** [comment]
@kolen Did this get resolved?

**Comment by louim** [comment]
@rebelagentm I think we are experiencing the same issue. Happy to send the repo where it's happening if that's helpful.

**Comment by rebelagentm** [comment]
@louim Yes, please.  That will help us troubleshoot.  If it's a private repo, you can e-mail us at `dependabot-support@github.com` and reference this issue number.  Otherwise, just reply to this issue.  Thank you!

**Comment by rebelagentm** [comment]
This got resolved via our support channel.

**Comment by kolen** [comment]
The problem still persists in our repositories. And there's no way to "run update" or something like that.

**Comment by kolen** [comment]
I created a repo trying to reproduce this issue: https://github.com/kolen/dependabot_cfg_test, and another repo with the way around, where config was created **_before_** adding repo to dependabot (it's added automatically! Wow!): https://github.com/kolen/dependabot_cfg_test_2.

Both are working now.

But it might sometimes not work (different conditions and timing). We still have 2 repos with config that's not recognized by Dependabot (configuration UI shows when pressing configure button). And there's no way to refresh config status manually.
