### ISSUE TITLE
500 on profile page

### ISSUE THREAD

**Issue by badsyntax** [dependabot/feedback#926]
When visiting my profile page (https://app.dependabot.com/accounts/badsyntax/), I get the following error:

<img width="1020" alt="Screenshot 2020-05-06 at 20 28 14" src="https://user-images.githubusercontent.com/102141/81219863-53365900-8fd8-11ea-8750-ef5488666b95.png">

This request is failing with 500: https://api.dependabot.com/repos?account-id=[redacted]&account-type=user&page=1&installation-state=active

**Comment by schigh** [comment]
I can confirm that this is happening for me as well, both through the web interface, as well as through the API.  

Note that through the API, it is only happening for `active` installs.

request
```
GET /repos?account-id=[redacted]&account-type=org&installation-state=active&lockfile-only=true&page=1 HTTP/1.1
Authorization: Personal [redacted]
Host: api.dependabot.com
Connection: close
User-Agent: Paw/3.1.10 (Macintosh; OS X/10.15.4) GCDHTTPRequest
```
response
```
HTTP/1.1 500 Internal Server Error
Server: Cowboy
Date: Wed, 06 May 2020 19:53:51 GMT
Connection: close
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin-when-cross-origin
Content-Type: application/json; charset=utf-8
X-Request-Id: 938dc34c-f4a9-45c6-9c34-3eea290bbf40
X-Runtime: 0.786419
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Transfer-Encoding: chunked
Via: 1.1 vegur

{"errors":[{"status":500,"title":"Internal Server Error"}]}
```

**Comment by jurre** [comment]
Hey, this was indeed an issue on our side, a fix has been deployed so things should be back to normal, apologies for any inconvenience!

**Comment by badsyntax** [comment]
Hey. Unfortunately I'm still getting this error. I've signed out and back again, and get the same 500 on the same endpoint.

**Comment by badsyntax** [comment]
I've tried again and it appears to be fixed now. Thanks!

**Comment by jurre** [comment]
Thanks for reporting back @badsyntax, we indeed pushed out another related fix after my reply yesterday, I forgot to update you here. Happy to hear it's working again!
